---
resources:
- name: source-code
  type: git
  source:
    uri: https://github.com/gunayus/concourse-tutorial.git

jobs:
  - name: package
    plan:
    - get: source-code
      trigger: true
    - task: package
      privileged: true
      file: source-code/concourse/tasks/package.yml
