platform: linux

image_resource:
  type: docker-image
  source:
    repository: maven
    tag: latest

inputs:
  - name: source-code

outputs:
  - name: build-output

run:
  path: source-code/concourse/tasks/package.sh

params:
  MAVEN_BASEDIR: source-code
